[project]
site_name = "zyx"
site_description = "fun llm functions"
site_author = "Hammad Saeed"
site_url = "https://hammad.app/zyx"

copyright = """
Copyright &copy; 2026 Hammad Saeed
"""

extra_css = ["stylesheets/extras.css"]

nav = [
    {"Getting Started" = [
        {"Introduction" = "index.md"},
        {"Installation" = "getting-started/installation.md"}
    ]},
    {"Core Concepts" = [
        {"Semantic Operations" = "core-concepts/semantic-operations.md"},
        {"Context & Prompting" = "core-concepts/context.md"},
        {"Attachments" = "core-concepts/attachments.md"},
        {"Tool Use" = "core-concepts/tool-use.md"},
    ]},
    {"Context" = [
        {"Prompting" = "context/prompting.md"},
        {"Context Spans" = "context/spans.md"},
        {"Memory" = "context/memory.md"},
    ]},
    {"Attachments" = [
        {"Resources" = "attachments/resources.md"},
        {"Snippets" = "attachments/snippets.md"},
    ]},
    {"Semantic Operations" = [
        {"Make" = "semantic-operations/make.md"},
        {"Run" = "semantic-operations/run.md"},
        {"Edit" = "semantic-operations/edit.md"},
        {"Query" = "semantic-operations/query.md"},
        {"Evaluate" = "semantic-operations/evaluate.md"},
        {"Parse" = "semantic-operations/parse.md"},
    ]},
]

# ----------------------------------------------------------------------------
# Section for configuring theme options
# ----------------------------------------------------------------------------
[project.theme]

language = "en"

features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "header.autohide",
    "navigation.footer",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.path",
    "navigation.prune",
    "navigation.top",
    "navigation.sections",
    "navigation.tracking",
    "search.highlight",
    "toc.follow",
]

# ----------------------------------------------------------------------------
# In the "palette" subsection you can configure options for the color scheme.
# You can configure different color # schemes, e.g., to turn on dark mode,
# that the user can switch between. Each color scheme can be further
# customized.
#
# Read more:
# - https://zensical.org/docs/setup/colors/
# ----------------------------------------------------------------------------
primary = "custom"
accent  = "custom"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.font]
text = "Quicksand"
code = "Google Sans Code"

[project.theme.icon]
logo = "lucide/smile"
repo = "lucide/smile"

# ----------------------------------------------------------------------------
# The "extra" section contains miscellaneous settings.
# ----------------------------------------------------------------------------
[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/hsaeed3/zyx"

[project.markdown_extensions.abbr]

[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.tilde]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.attr_list]
[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"
[project.markdown_extensions.md_in_html]

[project.markdown_extensions.def_list]
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true

[project.markdown_extensions.footnotes]

[project.markdown_extensions.tables]
